---
- hosts: sandbox
  become: true
  tasks:
    - name: Update apt packages list
      command: sudo apt-get update

    - name: Install essential packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Install git
      apt:
        name: git
        state: present
